# Generated by Django 4.1.7 on 2023-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0004_usersession_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
