# Generated by Django 4.1.7 on 2023-04-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0005_alter_usersession_logout_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
