# Generated by Django 4.1.7 on 2023-04-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0008_useractivity_delete_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
