# Generated by Django 4.1.7 on 2023-04-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0009_useractivity_first_name_useractivity_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
