# Generated by Django 4.1.7 on 2023-04-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0011_useractivity_change_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='change_message',
        ),
    ]
