# Generated by Django 4.1.7 on 2023-04-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0012_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={},
        ),
    ]
