# Generated by Django 4.1.7 on 2023-04-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0015_rename_mymodel_mymodel1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel1',
            new_name='Model1',
        ),
    ]
