# Generated by Django 4.1.7 on 2023-04-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0016_rename_mymodel1_model1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1',
        ),
    ]
